--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/24/2021 11:42:16 PM
-- Server version: 8.0.16
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE eddieshop;

--
-- Drop table `admin`
--
DROP TABLE IF EXISTS admin;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Set default database
--
USE eddieshop;

--
-- Create table `user`
--
CREATE TABLE user (
  UserID char(36) NOT NULL COMMENT 'Khoá chính',
  Name varchar(100) NOT NULL COMMENT 'Tên đăng nhập',
  Code varchar(20) NOT NULL COMMENT 'Mã người dùng',
  PassWord varchar(30) NOT NULL COMMENT 'Mật khẩu',
  DisplayName varchar(100) NOT NULL DEFAULT 'Admin' COMMENT 'Tên hiển thị',
  Type int(1) NOT NULL DEFAULT 0 COMMENT 'Loại quản trị viên',
  Description varchar(255) DEFAULT NULL COMMENT 'Mô tả',
  Email varchar(100) DEFAULT NULL COMMENT 'Email',
  Phone varchar(25) DEFAULT NULL COMMENT 'Số điện thoại',
  SessionID char(36) DEFAULT NULL COMMENT 'Id phiên đăng nhập',
  ConnectionID varchar(25) DEFAULT NULL COMMENT 'Id kết nối client',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Người tạo mới',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo mới',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người chỉnh sửa',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa',
  PRIMARY KEY (UserID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Thông tin người dùng';

--
-- Create table `admin`
--
CREATE TABLE admin (
  AdminID char(36) NOT NULL COMMENT 'Khoá chính',
  Name varchar(100) NOT NULL COMMENT 'Tên đăng nhập',
  Code varchar(20) NOT NULL COMMENT 'Mã quản trị viên',
  PassWord varchar(30) NOT NULL COMMENT 'Mật khẩu',
  DisplayName varchar(100) NOT NULL DEFAULT 'Admin' COMMENT 'Tên hiển thị',
  Type int(1) NOT NULL DEFAULT 0 COMMENT 'Loại quản trị viên',
  Description varchar(255) DEFAULT NULL COMMENT 'Mô tả',
  Email varchar(100) DEFAULT NULL COMMENT 'Email',
  Phone varchar(25) DEFAULT NULL COMMENT 'Số điện thoại',
  SessionID char(36) DEFAULT NULL COMMENT 'Id phiên đăng nhập',
  ConnectionID varchar(25) DEFAULT NULL COMMENT 'Id kết nối client',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Người tạo mới',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo mới',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người chỉnh sửa',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa',
  PRIMARY KEY (AdminID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Thông tin quản trị viên';

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
('1731fa87-79fd-4cc1-6978-553c0310877a', 'username0001', 'User-0001', '12345678@User', 'Nguyễn Tiến Dũng', 0, 'Suscipit et sed. Doloribus consequuntur ea. Dolores eius et. Nihil blanditiis voluptates. Iste fugit similique? Quia qui et. Ut assumenda vero. Natus...', 'user0001@gmail.com', '(465) 098-1888', '48d04691-671b-2f98-de69-4afe230d73a5', 'CEJhxePugBWcaifLFCMMJw', 'NTDUNG', '2016-09-21 05:35:43', 'NTDUNG', '1975-01-07 07:45:20'),
('185f84ed-4563-51a0-cac7-6c0aeb6ec302', 'username0002', 'User-0002', '12345678@User', 'Nguyễn Đình Hải Dương', 0, 'Facilis animi a. Fugiat saepe inventore; et eum animi. Ut tenetur animi. Aspernatur et veniam. Quae placeat dolorem. Voluptas dolores unde. Ea vel sit. Sed.', 'user0005@gmail.com', '(784) 105-7292', '174b8763-2707-7cb1-3c71-153b37881afe', 'butCxfafImA0asxNrJuElQ', 'NTDUNG', '2002-08-31 23:39:28', 'NTDUNG', '2017-04-17 18:59:15'),
('19165ed7-212e-21c4-0428-030d4265475f', 'username0003', 'User-0003', '12345678@User', 'Nguyễn Phương Hoa', 1, 'Eaque commodi est. Qui at optio; rem quisquam sit. Nemo et nihil; ut libero ea. Beatae est unde? Et est aut.', 'user0006@gmail.com', '(141) 952-2282', '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '31170', 'NTDUNG', '1998-03-13 20:26:43', 'NTDUNG', '1990-12-17 04:56:05'),
('27366e4a-5248-12e3-e312-ebbbcf065d1c', 'username0004', 'User-0004', '12345678@User', 'Nguyễn Mỹ Hạnh', 0, NULL, NULL, NULL, NULL, '41347', NULL, NULL, NULL, NULL),
('2924c34d-68f1-1d0a-c9c7-6c0aeb6ec302', 'username0005', 'User-0005', '12345678@User', 'Nguyễn Phương Thảo', 1, 'Quisquam ut suscipit accusantium omnis vero alias.', 'user0003@gmail.com', '(450) 290-3993', '43a6bdf5-1b6b-451b-3695-2c566fa88632', '25421', 'NTDUNG', '1974-06-22 22:31:21', 'NTDUNG', '1970-01-01 00:31:40'),
('3631011e-4559-4ad8-b0ad-cb989f2177da', 'username0006', 'User-0006', '12345678@User', 'Đào Thị Anh', 0, 'Aliquam perspiciatis quasi. Necessitatibus voluptas quos. Omnis minus voluptatem? Tempora earum quidem. Cum tempore porro. Est tempora error. Qui error et.', 'user0009@gmail.com', '(423) 916-0439', '674934cc-42cf-20cf-1d4a-aea48a10ed18', '77059', 'NTDUNG', '1971-03-25 02:56:21', 'NTDUNG', '1970-01-01 00:00:07'),
('471530a2-44fe-7395-b1ad-cb989f2177da', 'username0007', 'User-0007', '12345678@User', 'Nguyễn Đình Mạnh', 1, 'Aut sunt delectus. Delectus voluptatem molestias fugiat! Maiores ipsum magni nam et vel. Et dolorem illo! Officia doloremque unde.', 'user0005@gmail.com', '(730) 123-8017', '6fcbca4a-7938-4339-51cb-b8d37b68af4d', '64201', 'NTDUNG', '1970-01-01 00:08:53', 'NTDUNG', '1992-07-19 23:11:29'),
('4cf2dd43-5f4b-71b6-e212-ebbbcf065d1c', 'username0008', 'User-0008', '12345678@User', 'Trần Văn Hiểu', 1, 'Qui harum officiis. Unde repellendus beatae cumque. Nulla nihil quo rerum consequuntur dolorem? Ea alias omnis quos sit maxime. Laudantium adipisci culpa...', 'user0007@gmail.com', '(465) 824-3043', '438598e2-2574-4fc8-2626-978952f080e4', '26120', 'NTDUNG', '1974-03-07 08:35:55', 'NTDUNG', '1970-01-01 00:00:01'),
('5f7b48e5-16f9-2f2f-ecdc-845b5dcdad45', 'username0009', 'User-0009', '12345678@User', 'Bùi Anh Tuấn', 0, 'Quia aut commodi. Est aut iure delectus iusto. Animi non perspiciatis quis ut quia! Quaerat numquam et quia blanditiis voluptas eius. Voluptatem fuga et...', 'user0006@gmail.com', '(219) 687-2284', '2b5f15b9-17d9-57e8-1e4a-aea48a10ed18', 'eiLY0wtfN7hSeVjX3N0avQ', 'NTDUNG', '2002-11-05 04:58:39', 'NTDUNG', '1977-12-08 05:26:23'),
('7a0b757e-41eb-4df6-c6f8-494a84b910f4', 'username0010', 'User-0010', '12345678@User', 'Đinh Mạnh Ninh', 0, 'Error nesciunt illum. Vel ad dolorum. Voluptas soluta fugit; distinctio fugit vel? Eum quia et. Omnis sit expedita. Natus minus nobis!', 'user0005@gmail.com', '(375) 580-5172', '34bd2cef-5026-567c-3b71-153b37881afe', 'sOO3I9HPih-DdjvzmIPo4g', 'NTDUNG', '1994-08-12 16:56:12', 'NTDUNG', '1970-01-01 00:00:09');

-- 
-- Dumping data for table admin
--
INSERT INTO admin VALUES
('142cb08f-7c31-21fa-8e90-67245e8b283e', 'admin001', 'ADMIN-002', '12345678@Admin', 'Nguyễn Tiến Dũng', 0, 'Quản trị viên EddieShop', 'dungnt@gmai.com', '0123456789', '692d207a-12fe-54e6-6351-12b245ff3d02', 'INkA4Eff-h3aiZNdjapKHw', 'NTDUNG', '1970-01-01 00:07:13', 'NTDUNG', '1970-01-01 00:00:04'),
('469b3ece-744a-45d5-957d-e8c757976496', 'admin002', 'ADMIN-001', '12345678@Admin', 'Nguyễn Phương Thảo', 1, 'Quản trị viên EddieShop', 'dungnt@gmai.com', '0123456789', '77b3727c-71c0-3b4d-0cca-194e61bec35f', '57cdf8c4-47e3-5560-7e41-c', 'NTDUNG', '1986-12-14 19:08:29', 'NTDUNG', '2005-08-18 12:14:49');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;